const DEFAULT_BLUE_COLOR = '#0CAAD6';
const GREEN_COLOR = '#009688';
const RED_COLOR = '#9A0007';
const YELLOW_COLOR = '#FBBC00';
const PURPLE_COLOR = '#6C63FF';

export const DEFAULT_SUBJECT_COLOR = DEFAULT_BLUE_COLOR;
export const ECONOMY_COLOR = YELLOW_COLOR;
export const MATH_COLOR = RED_COLOR;
export const IT_COLOR = GREEN_COLOR;
